=== rajico/xml/xml/ejercicio11-2.dtd
<!ELEMENT partidos (partido+)>
<!ELEMENT partido (equipo_local,equipo_visitante)>
<!ELEMENT equipo_local (nombre)>
<!ELEMENT equipo_visitante (nombre)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST equipo_local goles (0|1|2|3|4) #REQUIRED>
<!ATTLIST equipo_visitante goles (0|1|2|3|4) #REQUIRED>

=== rajico/xml/xml/ejercicio11-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partidos SYSTEM "ejercicio11-2.dtd">
<partidos>
  <partido>
    <equipo_local goles="0">
      <nombre>Nottingham Presa</nombre>
    </equipo_local>
    <equipo_visitante goles="1">
      <nombre>Inter de Mitente</nombre>
    </equipo_visitante>
  </partido>
  <partido>
    <equipo_local goles="3">
      <nombre>Vodka Juniors</nombre>
    </equipo_local>
    <equipo_visitante goles="3">
      <nombre>Sparta da Risa</nombre>
    </equipo_visitante>
  </partido>
  <partido>
    <equipo_local goles="4">
      <nombre>Water de Munich</nombre>
    </equipo_local>
    <equipo_visitante goles="2">
      <nombre>Esteaua es del grifo</nombre>
    </equipo_visitante>
  </partido>
</partidos>
