=== rajico/xml/xml/ejercicio11-1.dtd
<!ELEMENT partidos (partido+)>
<!ELEMENT partido (equipo_local,equipo_visitante)>
<!ELEMENT equipo_local (nombre,goles)>
<!ELEMENT equipo_visitante (nombre,goles)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT goles (#PCDATA)>

=== rajico/xml/xml/ejercicio11-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partidos SYSTEM "ejercicio11-1.dtd">
<partidos>
  <partido>
    <equipo_local>
      <nombre>Nottingham Presa</nombre>
      <goles>0</goles>
    </equipo_local>
    <equipo_visitante>
      <nombre>Inter de Mitente</nombre>
      <goles>1</goles>
    </equipo_visitante>
  </partido>
  <partido>
    <equipo_local>
      <nombre>Vodka Juniors</nombre>
      <goles>3</goles>
    </equipo_local>
    <equipo_visitante>
      <nombre>Sparta da Risa</nombre>
      <goles>3</goles>
    </equipo_visitante>
  </partido>
  <partido>
    <equipo_local>
      <nombre>Water de Munich</nombre>
      <goles>4</goles>
    </equipo_local>
    <equipo_visitante>
      <nombre>Esteaua es del grifo</nombre>
      <goles>2</goles>
    </equipo_visitante>
  </partido>
</partidos>
