=== rajico/xml/ejerciciosclase/ejemplo1.dtd
<!ELEMENT personas (persona*)>
<!ELEMENT persona (nombre,mayoredad?,ciudad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mayoredad EMPTY>
<!ELEMENT ciudad (#PCDATA)>

=== rajico/xml/ejerciciosclase/ejercicioclase6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "ejemplo1.dtd">
<personas>
    <persona>
    <nombre>Rafael</nombre>
    <mayoredad/>
    <ciudad>Córdoba</ciudad>    
    </persona>
    
    <persona>
    <nombre>Dora la Exploradora</nombre>
    <ciudad>Medellin</ciudad>
    </persona>
</personas>
