=== rajico/xml/xsd/ejercicio4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="personas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="persona" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
              <xs:element name="datos" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    <xs:element name="apellidos" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    <xs:element name="dni" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
                <xs:element name="comentario" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
              </xs:sequence>
              <xs:attribute name="fecha_nacimiento" type="xs:date" use="required"/>
            </xs:complexType>
          </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rajico/xml/xsd/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio4.xsd">
	<persona fecha_nacimiento="1992-02-02">
		<datos>
			<nombre>Paquito</nombre>
			<apellidos>de los claveles</apellidos>
			<dni>12345678A</dni>
		</datos>
		<comentario>Es muy majo</comentario>
	</persona>
	<persona fecha_nacimiento="1993-03-03">
		<datos>
			<nombre>Perico</nombre>
			<apellidos>de los palotes</apellidos>
			<dni>87654321B</dni>
		</datos>
		<comentario>Está en todos sitios</comentario>
	</persona>
	<persona fecha_nacimiento="2019-12-20">
		<datos>
			<nombre>COVID</nombre>
			<apellidos>diecinueve</apellidos>
			<dni>19191919C</dni>
		</datos>
		<comentario>Viene de Wuhan</comentario>
	</persona>
</personas>
